site_name: staticwordpress
site_description: Python Package to Create, Manipulate and Analyze Website Sitemaps
site_author: SERP Wings

site_url: https://static-wordpress-docs.netlify.app/

repo_url: https://github.com/serpwings/static-wordpress
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Tutorial: tutorial.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list
  
theme: readthedocs

copyright: Â© Copyright 2023 SERP Wings